services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: help_sak
      POSTGRES_USER: helpsak
      POSTGRES_PASSWORD: helpsak
    ports:
      - "5434:5432"
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db