# Generated by Django 5.2.5 on 2025-08-15 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BranchInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('branch_code', models.CharField(max_length=255)),
                ('branch_name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255)),
                ('province', models.CharField(max_length=255)),
                ('mobile_number', models.CharField(max_length=255)),
                ('tel_6_digits', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='HelpdeskRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('branch_name', models.CharField(max_length=255)),
                ('device', models.CharField(max_length=255)),
                ('provider', models.CharField(max_length=255)),
                ('problem', models.CharField(max_length=255)),
                ('solution', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('by', models.CharField(max_length=255)),
                ('status', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='InternetLink',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('branch_name', models.CharField(max_length=255)),
                ('proivider', models.CharField(max_length=255)),
                ('fttx', models.CharField(max_length=255)),
                ('speed', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('last_service', models.DateField()),
                ('service_center', models.CharField(max_length=255)),
            ],
        ),
    ]
