# Generated by Django 5.2.5 on 2025-08-18 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='helpdeskrecord',
            name='branch_code',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='internetlink',
            name='branch_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='helpdeskrecord',
            name='device',
            field=models.CharField(choices=[('Aruba', 'Aruba'), ('Microtik', 'Microtik'), ('Microtik+Aruba', 'Microtik+Aruba'), ('Router', 'Router'), ('Aruba+Dlink', 'Aruba+Dlink'), ('Pc', 'Pc'), ('IP Phone', 'IP Phone'), ('SmartCARD', 'SmartCARD'), ('HUB', 'HUB'), ('ZIMBRA MAIL', 'ZIMBRA MAIL')], max_length=50),
        ),
        migrations.AlterField(
            model_name='helpdeskrecord',
            name='status',
            field=models.IntegerField(choices=[(1, 'แก้ไขแล้ว'), (2, 'กำลังรอดำเนินการ'), (3, 'กำลังจัดเตรียมอุปกรณ์')]),
        ),
    ]
